# Generated by Django 4.0.1 on 2022-02-06 19:41

from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Freq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Note', models.CharField(max_length=200)),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('DeviceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.device')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UpperWarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField()),
                ('FromDate', models.DateTimeField()),
                ('ToDate', models.DateTimeField(null=True)),
                ('SensorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('MaxValue', models.FloatField()),
                ('MinValue', models.FloatField()),
                ('Accuracy', models.FloatField()),
                ('MeasurementFreqID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.measurementfreq')),
                ('TypeOfMeasurementID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.typeofmeasurement')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='TypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.sensortype'),
        ),
        migrations.CreateModel(
            name='MeasuredValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('Value', models.FloatField()),
                ('Valid', models.BooleanField(blank=True, null=True)),
                ('SensorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='LowerWarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField()),
                ('FromDate', models.DateTimeField()),
                ('ToDate', models.DateTimeField(null=True)),
                ('SensorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='PlaceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='solar.place'),
        ),
    ]
