# Generated by Django 4.0.1 on 2022-02-06 19:45

from django.db import migrations
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuredvalue',
            name='Date',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=django.utils.timezone.now),
        ),
    ]
